[tool.poetry]
name = "orb"
version = "0.1.0"
description = ""
authors = ["Max Prosper <maxprosper22@gmail>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sanic = "^24.6.0"
toml = "^0.10.2"
python-dotenv = "^1.0.1"
asyncpg = "^0.29.0"
jinja2 = "^3.1.4"
sanic-ext = "^23.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
