[project]
name = "orb"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Max Prosper", email = "maxprosper22@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "sanic>=24.6.0,<25.0.0",
    "toml>=0.10.2,<0.11.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "asyncpg>=0.29.0,<0.30.0",
    "jinja2>=3.1.4,<4.0.0",
    "sanic-ext>=23.12.0,<24.0.0",
    "dynaconf>=3.2.10",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
